---
pagetitle: "Dokumentasi Aplikasi Web"
title: Aplikasi Web
subtitle: |
    Dokumentasi/Manual Aplikasi Web

title-block-banner: true

toc: true
sidebar: side-webapps

author: Taruma Sakti Megariansyah
date: 2022-11-21
reference-location: section
appendix-style: none
# date-modified: 2022-11-17

# abstract: |
#     Portal informasi aplikasi web yang dikembangkan oleh **fiako**dev.
---

**Aplikasi Web** (_Web Application_) adalah aplikasi yang dapat diakses melalui  _Web Browser_. Aplikasi web ini merupakan solusi teknologi untuk memudahkan para praktisi ataupun akademisi dalam menyelesaikan masalah yang dihadapi. Aplikasi web ini juga digunakan sebagai demonstrasi pemanfaatan teknologi bahasa pemrograman [_python_] sebagai _tool_ dan _skill_ yang dapat memudahkan pekerjaan. 

Per November 2022, terdapat tiga aplikasi web yang telah dikembangkan dan dapat digunakan dalam pekerjaan. Ketiga aplikasi tersebut digabung menjadi satu paket aplikasi web yang dinamai sebagai "Aplikasi Pengolahan Data Hujan". Artikel mengenai aplikasi bisa baca di halaman [Artikel: Aplikasi Pengolahan Data Hujan](/webapps/webapps-rainfall.qmd). 

::: {.column-page}

_codename_ | Judul Aplikasi | Versi | Deskripsi Singkat | _Live App_ | _Source Code_ | Oleh
:- | :- | :-: | :- | :-: | :-:
`fiako-stations` | _Rainfall Stations Explorer_ | `v3.1.x` | Eksplorasi stasiun data hujan harian | [Heroku](https://demo-fiako-stations.herokuapp.com) \| [Render](https://demo-fiako-stations.onrender.com) | [GitHub](https://github.com/fiakoenjiniring/demo-stations) | TSM
`hidrokit-rainfall` | _Rainfall Data Explorer_ | `v1.3.x` | Eksplorasi dan analisis data hujan harian | [Heroku](https://hidrokit-rainfall.herokuapp.com) \| [Render](https://hidrokit-rainfall.onrender.com) | [GitHub](https://github.com/fiakoenjiniring/rainfall) | TSM
`fiako-anfrek` | _Frequency Analaysis_ | `v1.1.x` | Menghitung parameter statistik hingga analisis frekuensi | [Heroku](https://fiako-anfrek.herokuapp.com) \| [Render](https://fiako-anfrek.onrender.com) | [GitHub](https://github.com/fiakoenjiniring/anfrek) | TSM

: [**Aplikasi Pengolahan Data Hujan**](/webapps/webapps-rainfall.qmd)

::: 

::: {.callout-note}
Aplikasi yang menggunakan layanan Heroku memiliki batasan kuota penggunaan maksimal 1000 jam/bulan.
:::

---

Aplikasi Web merupakan hasil tim penelitian dan pengembangan (_research and development_) [FIAKO Engineering] yang lebih dikenal sebagai [**fiako**dev].

[FIAKO Engineering]: https://fiako.engineering
[**fiako**dev]: https://dev.fiako.engineering
[_python_]: https://www.python.org/
