project:
  type: website
  preview: 
      port: 3637

execute: 
  freeze: auto

website:
  title: "fiako-manual | Dokumentasi & Manual oleh FIAKO Engineering"
  description: "Dokumentasi Manual oleh FIAKO Engineering"
  
  site-url: https://manual.fiako.engineering
  repo-url: https://github.com/fiakoenjiniring/manual
  repo-actions: [edit, issue]

  reader-mode: true
  search: 
    location: navbar
    type: overlay
  page-navigation: true

  # FOR TWITTER / open-graph
  image: /assets/logo-fiako-manual.png
  favicon: /assets/logo-fiako-manual.png

  ## NAVIGATION BAR
  navbar:
    title: fiako-manual
    background: dark
    # foreground: warning
    # pinned: false

    collapse: true

    logo: /assets/logo-fiako-manual.png

    left:
      - text: Home
        href: index.qmd
      - text: "**FIAKODEV-PROJECTS**"
        menu:
          - "---"
          - text: "_Water Resource Engineering_"
          - text: __FIAKO-HIDROKIT__
            href: "/#"
          - text: _Rainfall Web Apps_
            href: webapps/webapps-rainfall.qmd
          - "---"
          - text: "_Geotechnical Engineering_"
          - text: __FIAKO-SOLUMMAA__
            href: solummaa/index.qmd
          - text: "fiako-gpconverter"
            href: solummaa/gpconverter.qmd
          - text: "fiako-gptreader.xl"
            href: solummaa/gptreader-xl.qmd
          - "---"
          - text: "_Structural Engineering_"
          - text: "_planning_"
          - "---"
          - text: "_General_"
          - text: "_In Development_"
          - "---"
      - text: GREENHORN
        menu:
          - "---"
          - text: "_G22_"
          - text: "`G22.11.29` - __Mermaid.js & Interpolasi Linear__"
            href: greenhorn/G22-11-29.qmd
          - "---"
          - text: "_G23_"
          - text: "_In Development_"
          - "---"

    right:
      - icon: github
        href: https://github.com/fiakoenjiniring/manual

  sidebar:
    - id: side-webapps
      style: floating
      search: true
      border: true
      collapse-level: 1
      pinned: true
      contents:
        - text: "Ringkasan"
          href: webapps/index.qmd
        - webapps/webapps-rainfall.qmd
        - section: Tutorial _Rainfall Apps_
          contents:
            - text: "`fiako-stations`"
              href: tutorial/webapps/fiako-stations.qmd
            - text: "`hidrokit-rainfall`"
              href: tutorial/webapps/hidrokit-rainfall.qmd
            - text: "`fiako-anfrek`"
              href: tutorial/webapps/fiako-anfrek.qmd
        - "---"
    - id: side-solummaa
      style: floating
      search: true
      border: true
      collapse-level: 1
      pinned: true
      contents:
        - "<H3>FIAKODEV-PROJECTS: SOLUMMAA</H3>"
        - "---"
        - text: "FIAKO-SOLUMMAA"
          href: solummaa/index.qmd
        - "---"    
        - section: __SOLUMMAA PROJECTS__
          contents:
            - href: solummaa/gpconverter.qmd
            - href: solummaa/gptreader-xl.qmd
        - "---"    
        - section: _OTHER PROJECTS_
          contents:
            - text: "FIAKO-HIDROKIT"
              href: https://hidrokit.github.io
        - "---"    

  ## SIDEBAR
  page-footer:
    right: >-
      [open-source](https://github.com/fiakoenjiniring/manual) website by [**fiako**dev](https://dev.fiako.engineering)
    left: >-
      &copy; 2022-2023 PT. FIAKO ENJINIRING INDONESIA.
    # center:
    #   - "About"

  

format:
  html:
    theme: journal # spacelab, yeti, zephyr
    css: styles.css
    toc: true
    link-external-newwindow: true
    # language: language_id.yml



