project:
  type: website
  preview: 
      port: 3637

execute: 
  freeze: auto

website:
  title: "fiako-manual | Dokumentasi & Manual oleh FIAKO Engineering"
  description: "Dokumentasi Manual oleh FIAKO Engineering"
  
  site-url: https://manual.fiako.engineering
  repo-url: https://github.com/fiakoenjiniring/manual
  repo-actions: [edit, issue]

  reader-mode: true
  search: 
    location: navbar
    type: overlay
  page-navigation: true

  # FOR TWITTER / open-graph
  image: /assets/logo-fiako-manual.png
  favicon: /assets/logo-fiako-manual.png

  ## NAVIGATION BAR
  navbar:
    title: fiako-manual
    background: dark
    # foreground: warning
    # pinned: false

    collapse: true

    logo: /assets/logo-fiako-manual.png

    left:
      - text: Home
        href: index.qmd
      - text: HIDROKIT
        href: https://hidrokit.github.io/hidrokit
      - text: SOLUMMAA
        href: solummaa/index.qmd
      - text: Tutorial
        href: tutorial/index.qmd
      - text: Artikel
        menu: 
          - href: webapps/webapps-rainfall.qmd

    right:
      - text: Aplikasi Web
        href: webapps/index.qmd
      - text: "`G2X`"
        menu:
          - text: "`G22.11.29`"
            href: greenhorn/G22-11-29.qmd
      - icon: github
        href: https://github.com/fiakoenjiniring/manual

  sidebar:
    - id: side-webapps
      style: floating
      search: true
      border: true
      collapse-level: 1
      pinned: true
      contents:
        - text: "Ringkasan"
          href: webapps/index.qmd
        - webapps/webapps-rainfall.qmd
        - section: Tutorial _Rainfall Apps_
          contents:
            - text: "`fiako-stations`"
              href: tutorial/webapps/fiako-stations.qmd
            - text: "`hidrokit-rainfall`"
              href: tutorial/webapps/hidrokit-rainfall.qmd
            - text: "`fiako-anfrek`"
              href: tutorial/webapps/fiako-anfrek.qmd
        - "---"
    - id: side-solummaa
      style: floating
      search: true
      border: true
      collapse-level: 1
      pinned: true
      contents:
        - text: "FIAKO-SOLUMMAA"
          href: solummaa/index.qmd
        - "---"    
        - section: SOLUMMAA PROJECTS
          contents:
            - text: GPCONVERTER
              href: solummaa/gpconverter.qmd
            - text: GPTREADER.XL
              href: solummaa/gptreader-xl.qmd
          

  ## SIDEBAR
  page-footer:
    right: >-
      [open-source](https://github.com/fiakoenjiniring/manual) website by [**fiako**dev](https://dev.fiako.engineering)
    left: >-
      &copy; 2022-2023 PT. FIAKO ENJINIRING INDONESIA.
    # center:
    #   - "About"

  

format:
  html:
    theme: journal # spacelab, yeti, zephyr
    css: styles.css
    toc: true
    link-external-newwindow: true
    # language: language_id.yml



