project:
  type: website
  preview: 
      port: 3637
  

execute: 
  freeze: auto

website:
  title: "FIAKO Manual"
  description: "Dokumentasi Manual oleh FIAKO Engineering"
  
  site-url: https://manual.fiako.engineering
  repo-url: https://github.com/fiakoenjiniring/manual
  repo-actions: [edit, issue]

  reader-mode: true
  search: 
    location: navbar
    type: overlay
  page-navigation: true

  # FOR TWITTER / open-graph
  image: "fiakologo.png"
  favicon: "fiakologo.png"

  ## NAVIGATION BAR
  navbar:
    title: fiako-manual
    background: dark
    # foreground: warning
    # pinned: false

    collapse: true

    logo: "fiakologo.png"

    left:
      # - text: Home
      #   href: index.qmd
      - text: Web Apps
        menu:
          - text: Ringkasan
            href: webapps/index.qmd
          - text: "Aplikasi Pengolahan Data Hujan"
            href: webapps/webapps-rainfall.qmd
      - text: Tutorial Web Apps
        menu:
          - text: "`fiako-stations`"
            href: tutorial/webapps/fiako-stations.qmd
          - text: "`hidrokit-rainfall`"
            href: tutorial/webapps/hidrokit-rainfall.qmd
          - text: "`fiako-anfrek`"
            href: tutorial/webapps/fiako-anfrek.qmd


    right:
      - icon: github
        href: https://github.com/fiakoenjiniring/manual
      - text: "`G2X`"
        menu:
          - text: "`G22.11.29`"
            href: greenhorn/G22-11-29.qmd

  sidebar:
    - id: side-home
      style: floating
      contents:
        - section: Manual
          contents:
            - "test 1 2 3"

    - id: side-webapps
      style: floating
      search: true
      border: true
      collapse-level: 1
      pinned: true
      contents:
        - text: "Ringkasan"
          href: webapps/index.qmd
        - webapps/webapps-rainfall.qmd
        - section: Tutorial _Rainfall Apps_
          contents:
            - text: "`fiako-stations`"
              href: tutorial/webapps/fiako-stations.qmd
            - text: "`hidrokit-rainfall`"
              href: tutorial/webapps/hidrokit-rainfall.qmd
            - text: "`fiako-anfrek`"
              href: tutorial/webapps/fiako-anfrek.qmd
        - "---"
          

  ## SIDEBAR
  page-footer:
    right: >-
      website by **fiako**dev, 
      built with [Quarto](https://quarto.org/).
    left: >-
      &copy; 2022 PT. FIAKO ENJINIRING INDONESIA.
    # center:
    #   - "About"

  

format:
  html:
    theme: yeti # spacelab, yeti, zephyr
    css: styles.css
    toc: true
    link-external-newwindow: true
    language: language_id.yml



