project:
  type: website
  preview: 
      port: 3637

execute: 
  freeze: auto

website:
  title: "FIAKO Manual"
  description: "Dokumentasi Manual oleh FIAKO Engineering"

  site-url: https://manual.fiako.engineering
  repo-url: https://github.com/fiakoenjiniring/manual
  repo-actions: [edit, issue]

  reader-mode: true
  search: 
    location: sidebar
    type: textbox
  page-navigation: true

  # FOR TWITTER / open-graph
  image: "fiakologo.png"
  favicon: "fiakologo.png"

  ## NAVIGATION BAR
  navbar:
    title: fiako-manual
    background: dark
    # foreground: warning
    # pinned: false

    collapse: true

    logo: "fiakologo.png"

    left:
      - text: Home
        href: index.qmd
      - text: Web Apps
        href: webapps/index.qmd

    right:
      - icon: github
        href: https://github.com/fiakoenjiniring/manual

  sidebar:
    - id: side-home
      style: floating
      contents:
        - section: Manual
          contents:
            - "test 1 2 3"

    - id: side-webapps
      style: docked
      search: true
      border: true
      collapse-level: 1
      pinned: true
      contents:
        - webapps/index.qmd
        - webapps/rainfall-apps.qmd
        - section: "`fiako-stations`"
          contents:
            - README
            - Penggunaan / Tutorial
        - section: "`hidrokit-rainfall`"
          contents:
            - README
            - Penggunaan / Tutorial
        - section: "`fiako-anfrek`"
          contents:
            - README
            - Penggunaan / Tutorial
        - "---"
          

  ## SIDEBAR
  page-footer:
    right: >-
      developed by **fiako**dev. 
      built with ❤️ and [Quarto](https://quarto.org/).
    left: >-
      &copy; 2022 PT. FIAKO ENJINIRING INDONESIA.

format:
  html:
    theme: yeti # spacelab, yeti, zephyr
    css: styles.css
    toc: true
    link-external-newwindow: true



