---
pagetitle: "G22.11.29: Mermaid.js dan Interpolasi Linear"
title: | 
    Mermaid.js dan Interpolasi Linear
subtitle: |
    Kegiatan Greenhorn (G2X) G22.11.29

toc: false
toc-location: right
sidebar: false

author-title: Pembicara
published-title: Diselenggarakan

language:
    title-block-modified: Diperbarui

page-layout: article

author: 
    - name: Taruma Sakti Megariansyah
    - name: LKO
date: 2022-11-28
date-modified: 2022-11-30
date-format: full
lang: id
aliases: 
  - /tutorial/greenhorn/2022-11-29.html
---

Halaman ini digunakan sebagai portal informasi terkait materi/sumber yang digunakan untuk _Greenhorn_ hari Selasa, 29 November 2022.

## Kegiatan

Kegiatan diadakan pada hari Selasa, 29 November 2022 secara _hybrid_ (Online + Offline) dengan lokasi _on-site_ di ruang meeting _FIAKO Engineering_. Durasi kegiatan selama 2 jam dari 9.15 WIB sampai 11.15 WIB. 

## Agenda

Agenda _greenhorn_ antara lain:

1. [General] Instalasi VSCode dan extension mermaid.js
2. [Mermaid] Demonstrasi penggunaan mermaid.js di VSCode. 
3. [Excel] Studi kasus implementasi interpolasi linear menggunakan _dynamic array_ / `LAMBDA`.

## Persiapan sebelum G22.11.29

Berikut materi yang harus dibaca/dilakukan sebelum `G22.11.29`:

- Install VSCode. VSCode bisa didownload di [halaman VSCode](https://code.visualstudio.com/). Instalasinya cukup sederhana dengan mengikuti petunjuknya.

- Extension yang digunakan untuk mermaid.js adalah:
    - [ext: Mermaid Editor](https://marketplace.visualstudio.com/items?itemName=tomoyukim.vscode-mermaid-editor) (untuk editor .mmd). 
    - (Opsional) [ext: Markdown Preview Mermaid](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-mermaid) (untuk preview mermaid di markdown).

- Mereview ulang materi G2X feidlambda II. Berikut presentasi [Greenhorn feidlambda II: Exploring Dynamic Array + User Defined Lambda (UDL)](https://lambda.fiako.engineering/greenhorn/feidlambda-2/presentation.html#/title-slide).

## Materi/Sumber

Berikut materi/sumber di G22.11.29:

- Folder mermaid `G22.11.29` di [onedrive](https://1drv.ms/f/s!AmxSTa4UunElh4wGmca6BOU4gCuFyQ) (password: `G22.11.29`).
- Excel implementasi interpolasi linear: [G22.11.29_interpolasi_linear.xlsx](https://1drv.ms/x/s!AmxSTa4UunElh4xA2Ktk2o9ctzb91w?e=2iUTt6) (password: `G22.11.29`).

## Rekaman G2X

Rekaman G22.11.29 bisa diakses di `XAGANT::TSM::05 VIDEO LEARNING::greenhorn::G22.11.29_mermaid-and-linear-interpolation.mp4`. 

## Evaluasi G22.11.29

Yang harus ditambahkan:

- [ ] Tutorial pengaturan dan penggunaan mermaid.js di VSCode.

Untuk kedepannya:

- Membuat panduan jelas sebelum mengikuti greenhorn `G2X` yang terkait dengan instalasi aplikasi. Bagi yang belum menginstall diharapkan hadir 30 menit sebelum kegiatan `G2X`. 
- 30 menit sebelum kegiatan akan digunakan sebagai _review_ materi sebelum kegiatan `G2X`.